ALTER TABLE `DITIB_PLACES` add `EMAIL`   varchar(80) DEFAULT NULL;
ALTER TABLE `DITIB_PLACES` add `FAX`     varchar(80) DEFAULT NULL;
ALTER TABLE `DITIB_PLACES` add `PHONE`   varchar(80) DEFAULT NULL;
ALTER TABLE `DITIB_PLACES` add `WEBSITE` varchar(80) DEFAULT NULL;
