ALTER TABLE `DITIB_PLACES` add `CREATION_TIME`     datetime DEFAULT NULL;
ALTER TABLE `DITIB_PLACES` add `MODIFICATION_TIME` datetime DEFAULT NULL;

UPDATE `DITIB_PLACES` set `CREATION_TIME` = NOW()     where `CREATION_TIME` IS NULL;
UPDATE `DITIB_PLACES` set `MODIFICATION_TIME` = NOW() where `MODIFICATION_TIME` IS NULL;
